workflows:
  ios_prep_unsigned:
    name: iOS prep (unsigned)
    environment:
      flutter: stable
    scripts:
      - name: Setup
        script: |
          flutter clean
          flutter pub get
          flutter analyze
      - name: Build iOS (unsigned)
        script: |
          flutter build ios --release --no-codesign
      - name: Build Android (optional)
        script: |
          flutter build apk --release
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/app/outputs/**/*.apk
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - ~/.gradle/caches

  ios_testflight_manual:
    name: iOS TestFlight (manual signing)
    environment:
      flutter: stable
      groups:
        - app_store_connect        # enthält: APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY
        - app                      # enthält: BUNDLE_ID=de.mailsmart.cruiseplanner
    scripts:
      - name: Setup
        script: |
          flutter clean
          flutter pub get

      - name: Install uploaded certificates
        script: |
          # installiert alle in Codemagic hochgeladenen .p12/.mobileprovision
          keychain add-certificates

      - name: Apply provisioning profiles to Xcode project
        script: |
          # weist das passende Profil deiner Bundle-ID zu
          xcode-project use-profiles --bundle-id $BUNDLE_ID

      - name: Build signed IPA
        script: |
          flutter build ipa --release

    publishing:
      app_store_connect:
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        key_id:   $APP_STORE_CONNECT_KEY_IDENTIFIER
        api_key:  $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true
        beta_groups:
          - Internal Testers

    artifacts:
      - build/ios/ipa/*.ipa