workflows:
  ios_prep_unsigned:
    name: iOS prep (unsigned)
    environment:
      flutter: stable
    scripts:
      - name: Setup
        script: |
          flutter clean
          flutter pub get
          flutter analyze
      - name: Build iOS (unsigned)
        script: |
          flutter build ios --release --no-codesign
      - name: Build Android (optional)
        script: |
          flutter build apk --release
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/app/outputs/**/*.apk
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - ~/.gradle/caches

  ios_testflight_ready:
    name: iOS TestFlight
    environment:
      flutter: stable
      groups:
        - app_store_connect   # APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY
        - app                 # BUNDLE_ID = z. B. de.groth.cruiseplanner
      ios_signing:
        distribution_type: app_store
        bundle_identifier: $BUNDLE_ID   # exakt wie bei Apple registriert
    scripts:
      - name: Setup
        script: |
          flutter clean
          flutter pub get
          flutter analyze
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build signed IPA
        script: |
          flutter build ipa --release
    publishing:
      app_store_connect:
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        key_id:   $APP_STORE_CONNECT_KEY_IDENTIFIER
        api_key:  $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
    artifacts:
      - build/ios/ipa/*.ipa
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
