workflows:
  ios_testflight_ready:
    name: iOS TestFlight
    environment:
      flutter: stable
      groups:
        - app_store_connect   # enthält die 3 Secrets
        - app                 de.mailsmart.cruiseplanner
    scripts:
      - name: Setup
        script: |
          flutter clean
          flutter pub get
          flutter analyze
      - name: Build iOS (signed IPA)
        script: |
          flutter build ipa --release
    ios_signing:
      app_store_connect:
        issuer_id: 085932f5-7e86-454e-933d-8b46d6abcf97
        key_id: FJ5698LG5N
        api_key: -----BEGIN PRIVATE KEY-----/
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgQoIe2urDjI48D/XN/
Y0IOnLws9Ps4NQUKBlse1Z7j36OgCgYIKoZIzj0DAQehRANCAASv/wRG+fE70YHJ/
2y9blrZcAeu+wh4YeFg91go/9uIGVCHbRCh5+kNW8IIzQEJ38NIWBgr3TMPgWCDh/
Wr04ydZd/
-----END PRIVATE KEY-----
      provisioning_profiles:
        - bundle_identifier: de.mailsmart.cruiseplanner
          export_method: app-store
    publishing:
      app_store_connect:
        auth:
          issuer_id: 085932f5-7e86-454e-933d-8b46d6abcf97
          key_id: FJ5698LG5N
          api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/Runner.app
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
