workflows:
  ios_prep_unsigned:
    name: iOS prep (unsigned)
    environment:
      flutter: stable
    scripts:
      - name: Setup
        script: |
          flutter clean
          flutter pub get
          flutter analyze
      - name: Build iOS (unsigned)
        script: |
          flutter build ios --release --no-codesign
      - name: Build Android (optional)
        script: |
          flutter build apk --release
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/app/outputs/**/*.apk
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - ~/.gradle/caches

  ios_testflight_ready:
    name: iOS TestFlight (auto signing)
    environment:
      flutter: stable
      groups:
        - app                  # enthält: BUNDLE_ID=de.mailsmart.cruiseplanner
      ios_signing:
        distribution_type: app_store
        bundle_identifier: $BUNDLE_ID
    scripts:
      - name: Setup
        script: |
          flutter clean
          flutter pub get

      - name: Apply signing profiles
        script: |
          xcode-project use-profiles

      - name: Build signed IPA
        script: |
          flutter build ipa --release

    publishing:
      app_store_connect:
        submit_to_testflight: true
        beta_groups:
          - Internal Testers

    artifacts:
      - build/ios/ipa/*.ipa

    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache